### ISSUE TITLE
Не работает insert значения в комплекс

### ISSUE THREAD

**Issue by vosafonov** [tsu-iscd/lyapas-lcc#105]
Программа выводит только 1. Похоже на то, что не изменяется мощность комплекса.
Лучше поправить сначала https://vk.com/away.php?to=https%3A%2F%2Fgithub.com%2Ftsu-iscd%2Flyapas-lcc%2Fissues%2F104&cc_key=
После фикса 104 бага будет проще понять что происходит тут, т.к. сейчас даже мощность не можем вывести на экран.

```
main(/)
    @+F1(10)
    10⇒q 12345⇒a
    
    §1 a;q⇒b a/q⇒a 48+b@>F1.0 ↑(a≠0)1 
    §2 /F1>C
**
```

**Comment by MashaSamoylova** [comment]
![screenshot from 2018-10-01 12-08-52](https://user-images.githubusercontent.com/19507144/46270690-20fa8500-c573-11e8-9f87-6d2f312afdfe.png)
![screenshot from 2018-10-01 12-10-15](https://user-images.githubusercontent.com/19507144/46270691-21931b80-c573-11e8-8080-b4437e3cbc33.png)
Есть подозрение, что мощность и емкость перепутаны
после фикса бага 104 не починилось -_0_0_-

**Comment by MashaSamoylova** [comment]
Ошибка в `im1_im2`, `S1` и `Q1` действительно там путаются.
