### ISSUE TITLE
Исправить трансляцию операцию insert_element_in_complex

### ISSUE THREAD

**Issue by vosafonov** [tsu-iscd/lyapas-lcc#24]
На данный момент:
```
im2:
   {
      "args" : [ "L1[1]" ],
      "cmd" : "insert_element_in_complex",
      "type" : "cmd"
   }

или

   {
      "args" : [ "L1" ],
      "cmd" : "insert_element_in_complex",
      "type" : "cmd"
   }
```
Первый вариант не очень удачен. Возможно, стоит пофиксить im0_im1 или im1_im2, чтобы операция стала вот такой:
```
   {
      "args" : [ "L1", "1" ],
      "cmd" : "insert_element_in_complex",
      "type" : "cmd"
   }
```

Второй ваирант нужно попробовать переименовать в `insert_element_in_end_of_complex`, т.к. в таком случае операция явно описывает то, что она делает.

**Comment by SGrechnev** [comment]
Почему бы вместо `insert_element_in_end_of_complex` не использовать `push_in_complex` ?
По-моему, смысл очень даже понятен, и текста меньше => читабельнее код.

**Comment by vosafonov** [comment]
Ага, я опечатался, спасибо что заметил :)
Если сделать по аналогии с `С++` и назвать как `push_back_in_complex`, то согласен, так понятнее. Иначе не совсем ясно "куда вставляется элемент?", или вообще создается впечатление стека, где не важно куда вставляются элементы "в конец" или "в начало".

**Comment by SGrechnev** [comment]
Да, я имел в виду `push_back...` =)
