### ISSUE TITLE
im_program_printer.py не работает после im2_im3

### ISSUE THREAD

**Issue by MashaSamoylova** [tsu-iscd/lyapas-lcc#37]
`cat my_ex.lyapas | ../lyapas_to_json.py |./lyapas_im0 |./im0_im1 | ./im1_im2 | ./im2_im3 | ../im_program_printer.py`

```
definition main, /
create_complex F1, 100
create_complex F2, 100
definition f2, F1, /, F1
definition f1, k, /, F1
Traceback (most recent call last):
  File "../im_program_printer.py", line 41, in <module>
    main(args)
  File "../im_program_printer.py", line 34, in main
    args.out_file.write(convert(datum))
  File "../im_program_printer.py", line 23, in convert
    return datum["cmd"] + " " + ", ".join(process_args(datum)) + "\n"
KeyError: 'cmd'

```

my_ex.lyapas: 
```
main(/)
    @+F1(100)
    @+F2(100)
    *f2(F1/F1)
   **
f1(k/F1)
    k⇒F1.0
    **
f2(F1/F2)
    *f1(0/F1)
    **
```

**Comment by MashaSamoylova** [comment]
видимо кто-то описался в скрипте,

```
def convert(datum):
    datum_type = datum["type"]
    if datum_type == "cmd":
        return datum["cmd"] + " " + ", ".join(process_args(datum)) + "\n"
    elif datum_type == "label":
        return "label" + " " + str(datum["number"]) + "\n"
    elif datum_type == "definition":
        return "definition" + " " + ", ".join(process_args(datum)) + "\n"
    else:
        raise NameError('Unknown type "' + datum_type + '"')
```

вместо return datum['cmd'] должно быть "cmd"

**Comment by MashaSamoylova** [comment]
тогда на my_ex.lyapas отрабатывает вот так:

```
definition main, /
cmd F1, 100
cmd F2, 100
definition f2, F1, /, F1
definition f1, k, /, F1
cmd acc, k
cmd F1[0], acc
definition f2, F1, /, F2
definition f1, 0, /, F1

```

**Comment by vosafonov** [comment]
В этом случае мы получаем преобразование всех команд в `cmd`.

Т.е. был у нас `move F1, 100`, а получили мы `cmd F1, 100`.
В скрипте, как я понял, все ок.

Ошибка, как я понял, вот в чём: команда `move` в `im3` сейчас выглядит вот так
```   
{
  "args" : [ "F1[0]", "acc" ],
  "name" : "move",
  "type" : "cmd"
}
```

Тут нету ключа `cmd`, вот скрипт и падает с ошибкой `KeyError: 'cmd'`. (Кстати, тут можно выводить более информативное сообщение об ошибке). По факту, это баг в `im2_im3`, т.к. он пишет имя команды в поле `name`, а не `cmd`, как должно быть.

**Comment by vosafonov** [comment]
Этот баг уже пофиксили, но в отдельной ветке. Я сделал `cherry-pick` в `master`:
https://github.com/tsu-iscd/lyapas-lcc/commit/a44ae259929f5874333d7f1a6097759823f85d6f

Попробуй сейчас обновить мастер и посмотреть, падает ли скрипт на этом примере.
Если нет, то можно закрывать баг :)

**Comment by MashaSamoylova** [comment]
все хорошо
```
definition main, /
create_complex F1, 100
create_complex F2, 100
definition f2, F1, /, F1
definition f1, k, /, F1
move acc, k
move F1[0], acc
definition f2, F1, /, F2
definition f1, 0, /, F1

```
