### ISSUE TITLE
неизвестная ошибка при трансляции функции b2s(вывод числа на экран)

### ISSUE THREAD

**Issue by MashaSamoylova** [tsu-iscd/lyapas-lcc#38]
```
main(/)
    @+F1(100)
    *b2s(10, F1)

b2s(k/F1)
    k⇒e OF1
    e↪2
    §1 e↪3 e;10+'0'@>F1.0 e/10⇒e →1
    §2 '0'@>F1.0 
    §3 **

```

**Comment by vosafonov** [comment]
Похоже, что ошибка на этапе трансляции `im0_im1`.

**Comment by vosafonov** [comment]
Хе.
1) А `main` не должен заканчиваться символами `**`?
2) Вызов `b2s` содержит ошибку, т.к. в нём отсутствует `/`. Скорее всего должно быть: `*b2s(10/F1)`. Или я ошибаюсь?

**Comment by MashaSamoylova** [comment]
:D нет, не ошибаешься, всё правильно
