### ISSUE TITLE
Ошибка в трансляции индекса комплекса

### ISSUE THREAD

**Issue by vosafonov** [tsu-iscd/lyapas-lcc#60]
Если индекс является константой, то возникает проблема.

Вход 
```
{
    "args" : [ "8byte L1_struct[0]", 0 ],
    "cmd" : "move",
    "type" : "cmd"
}
```

Выход:
```
{
    "args" : [ "8byte l1[l2]", 0 ],
    "cmd" : "move",
    "type" : "cmd"
}
```

**Comment by vosafonov** [comment]
@MashaSamoylova, не забудь закрыть задачу после того, как сольём PR.

**Comment by vosafonov** [comment]
@MashaSamoylova. Я уже не помню, какой статус у задачи? Она уже выполнена или только в планах?

**Comment by MashaSamoylova** [comment]
@vosafonov выполнена
https://github.com/tsu-iscd/lyapas-lcc/pull/62
